name: oda
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.11.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py39hcbf5309_0
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1t=h2bbff1b_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=py39haa95532_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - python=3.9.16=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pywin32=227=py39hb82d6ee_1
  - pyzmq=23.2.0=py39hd77b12b_0
  - setuptools=65.6.3=py39haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tornado=6.2=py39hb82d6ee_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - zeromq=4.3.4=h0e60522_1
  - pip:
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - altair==4.2.2
    - anyio==3.6.2
    - async-timeout==4.0.2
    - attrdict==2.0.1
    - attrs==22.2.0
    - babel==2.12.1
    - bce-python-sdk==0.8.83
    - brotli==1.0.9
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - clip==1.0
    - coloredlogs==15.0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - cython==0.29.33
    - easydict==1.10
    - eiseg==1.1.1
    - entrypoints==0.4
    - fastapi==0.95.0
    - ffmpy==0.3.0
    - filelock==3.9.1
    - flask==2.2.3
    - flask-babel==3.0.1
    - flatbuffers==23.3.3
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - ftfy==6.1.1
    - future==0.18.3
    - gevent==22.10.2
    - geventhttpclient==2.0.2
    - gradio==3.24.1
    - gradio-client==0.0.5
    - greenlet==2.0.2
    - grpcio==1.53.0
    - h11==0.14.0
    - h5py==3.8.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - huggingface-hub==0.13.3
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.25.1
    - importlib-resources==5.12.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - kornia==0.6.10
    - kornia-moons==0.2.3
    - linkify-it-py==2.0.0
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.0
    - numpy==1.22.3
    - oda==2023.2.19.2
    - onnx==1.12.0
    - onnxruntime==1.14.1
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - orjson==3.8.9
    - packaging==21.3
    - paddleseg==2.7.0
    - pandas==1.5.3
    - pillow==9.1.0
    - prettytable==3.6.0
    - protobuf==3.20.0
    - pycocotools==2.0.6
    - pycparser==2.21
    - pycryptodome==3.17
    - pydantic==1.10.7
    - pydub==0.25.1
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - pyqtgraph==0.13.1
    - pyreadline3==3.4.1
    - pyrsistent==0.19.3
    - pytesseract==0.3.9
    - python-multipart==0.0.6
    - python-rapidjson==1.10
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qtpy==2.3.1
    - qudida==0.0.4
    - rarfile==4.0
    - regex==2023.3.23
    - requests==2.28.2
    - rfc3986==1.5.0
    - scikit-image==0.19.3
    - scikit-learn==1.2.1
    - scipy==1.10.1
    - seaborn==0.12.2
    - segments-ai==1.0.20
    - semantic-version==2.10.0
    - shapely==2.0.1
    - sklearn==0.0
    - sniffio==1.3.0
    - starlette==0.26.1
    - sympy==1.11.1
    - threadpoolctl==3.1.0
    - tifffile==2023.2.3
    - tokenizers==0.13.2
    - toolz==0.12.0
    - torch==2.0.0
    - torchvision==0.15.1
    - tqdm==4.65.0
    - transformers==4.27.3
    - tritonclient==2.32.0
    - types-pillow==9.4.0.17
    - types-requests==2.28.11.16
    - types-urllib3==1.26.25.8
    - uc-micro-py==1.0.1
    - urllib3==1.26.15
    - uvicorn==0.21.1
    - visdom==0.2.4
    - visdom-logger==0.1
    - visualdl==2.5.1
    - websocket-client==1.5.1
    - websockets==10.4
    - werkzeug==2.2.3
    - wget==3.2
    - x2paddle==1.4.1
    - yarl==1.8.2
    - zipp==3.14.0
    - zope-event==4.6
    - zope-interface==6.0
prefix: C:\Users\33433\anaconda3\envs\oda
